### ISSUE TITLE
color request

### ISSUE THREAD

**Issue by ohnonot** [GreenRaccoon23/archdroid-icon-theme#4]
since you so kindly offered it...

just to clarify, are you going to implement only exact colors from [here](https://www.google.com/design/spec/style/color.html#color-color-palette)?

i'd love to see darkest shades of bluegrey (#263238), deeporange (#bf360c) and brown (#3e2723).

thanks for this, it's a great icon theme.

**Comment by GreenRaccoon23** [comment]
No problem! I'll get to that tonight.

Yeah, Android provided the inspiration for and majority of the icons for this theme, so I'm sticking to Android's material design color palette plus Arch Linux's blue.

If you want to add your own color on your local computer, you could run this command on the `Archdroid-Green` folder to change the colors:

``` bash
find "Archdroid-Green" -type f -name "*.svg" -exec perl -pi -w -e 's/#4CAF50/#YOUR_RGB_COLOR/g;' {} \;;
```

I haven't tested this so be careful. That's a powerful command.

**Comment by ohnonot** [comment]
Thanks!
while trying out the above command, i noticed a broken link:
`Archdroid-Green/mimetypes/scalable/application-x-ruby.svg` points to `%f`.

**Comment by GreenRaccoon23** [comment]
Thanks for pointing that out! Just fixed it, and I'll be pushing it up soon. If you're curious, the `%f` comes from a bad thunar custom action/script I was using.

I'm adding those colors right now. I use the `svg-edit` binary to change the colors of the images, and apparently I lost my original source code for it, so I've been refactoring it. It's been fun because now it can edit 757 images in 0.1 seconds.

**Comment by ohnonot** [comment]
actually the find/perl oneliner did me just fine, but thanks anyway!
