### ISSUE TITLE
Icons turned black after librsvg update

### ISSUE THREAD

**Issue by galexej** [GreenRaccoon23/archdroid-icon-theme#5]
After upgrading librsvg on arch (2:2.40.20-1 -> 2:2.41.2-1), all icons from this theme turned black. I am not sure whether this is a bug on their side or whether it's a legitimate result of their refactoring though... I just wanted to mention it here. :)

https://i.imgur.com/2lcEWPc.png

**Comment by actionless** [comment]
see the conversation starting from this comment:
https://github.com/nana-4/materia-theme/issues/195#issuecomment-355942980

**Comment by GreenRaccoon23** [comment]
Nice work both of you! You're right; it's an issue with with the way librsvg 2:2.41 parses the svg xml. I hope it's a bug and not a change in the svg standard because it's going to break most of the svgs out there right now. I'm guessing it's just a bug because it was a patch update (40 to 41) instead of a major update (2 to 3).

I implemented a work-around, so updating the package should fix this bug. I had to add it to every file manually though, so there's a good chance I missed a couple. If you notice anything strange, please let me know.
